### ISSUE TITLE
Dependencies aren't correct for LightGraphs

### ISSUE THREAD

**Issue by sbromberger** [djsegal/JuliaPackages.jl#3]
The list of direct (and transitive) dependencies for LightGraphs seems to include some from previous versions. Specifically, we no longer depend on CodecZlib. Arpack, or any of their dependencies.

Is there something I need to do to make sure the right info is displayed? Thanks.

**Comment by djsegal** [comment]
Working on it! Relevant lines are:

https://github.com/djsegal/JuliaPackages.jl/blob/a427744a5f6eb239e34fd19adbc19101c7646a6d/src/scrape_general_packages.jl#L55-L66

**Comment by djsegal** [comment]
Is this fixed?
